version: '3.8'

services:
  check-app:
    build: .
    ports:
      - "8080:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
  
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: always

volumes:
  redis_data:
