# INSTRUCCIONES:
# Antes de desplegar, reemplaza TOKEN_AQUI con tu Personal Access Token de GitHub.
# El token debe tener permisos: Contents (Read-only).
# Ej: https://x-access-token:github_pat_XXXXX@github.com/...

version: '3.8'

services:
  check-app:
    image: node:20-slim
    container_name: check-app
    restart: always
    ports:
      - '3000:3000'
    expose:
      - '3000'
    volumes:
      - /home/data_check:/usr/src/app/persistence
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATA_PATH=/usr/src/app/persistence
    networks:
      - proxy-network
    entrypoint: []
    command: >
      sh -c "
      echo 'Init...' &&
      apt-get update && apt-get install -y git rsync ca-certificates &&
      mkdir -p /usr/src/app/persistence/system /usr/src/app/persistence/events /usr/src/app/persistence/uploads &&
      chmod -R 777 /usr/src/app/persistence &&
      rm -rf /tmp/app_new &&
      git clone --depth 1 https://x-access-token:TOKEN_AQUI@github.com/carlosh7/check.git /tmp/app_new &&
      rsync -av /tmp/app_new/. /usr/src/app/ &&
      rm -rf /tmp/app_new &&
      cd /usr/src/app &&
      npm install --omit=dev &&
      npm start"

networks:
  proxy-network:
    name: proxy-network
    driver: bridge